### ISSUE TITLE
Permitir a retirada de forma de envio

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-mandabem#10]
**Implementação para o APP**
Permitir que o usuário possa desativar formas de envio que não deseje utilizar. Temos uma demanda na comunidade onde a cliente deseje utilizar apenas uma das formas de envio do manda bem, pois o PAC Mini por correios ela não consegue. Logo, seria desativado PAC e SEDEX.

**Solução sugerida**
Em regras de envio ter um campo desabilitar, onde o cliente possa criar uma regra que terá a função de desabilitar para uma determinada faixa ou habilitada por padrão

**Comment by leomp12** [comment]
Nas regras de envio vai ficar confuso eu acho

**Comment by leomp12** [comment]
Mas dá pra fazer separado um array pra habilitar serviços para todos os CEPs e array de objetos para desabilitar por faixa

**Comment by matheusgnreis** [comment]
Valeu
